### ISSUE TITLE
Questions about Image segmentation on CamVid dataset

### ISSUE THREAD

**Issue by AGenchev** [TannerGilbert/Tutorials#15]
it's kind of issue (problem) but **not** error in the tutorial:
I get error when trying to run the trainer: `RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 1.96 GiB total capacity;...)`
nvidia-smi reports 1971MiB usage for the python3 process.
trying to investigate this, i thought that the program uploads the entire training data-set together with the  U-NET layers in the GPU .
My questions are is this the case and if so, is it possible to change the code to keep the training data out of the VRAM and create kind of a double-buffer in VRAM to upload the next few images while the first few are used to train to keep the GPU utilized but allow all this to run with 2 GB VRAM ?  
(many thanks for your tutorials)
Update: it could run if i skip `data.show_batch(2, figsize=(10, 7)) ` call then change `bs = 1 # was 2`
it ran until unfreeze operation, then it fails on second lr_find()

**Comment by TannerGilbert** [comment]
It doesn't load in all the images. Rather it only loads in n images where n is the batch_size. The reason it works when the model is frozen and doesn't work when it's unfrozen is because when you unfreeze the model it needs to update more weights therefore more vram is used. 

I also had the problem of having not enough vram a few times(eventhough I have 4GB). You can reduce VRAM usage by lowering the batch_size or lowering the image size.

And if you ever find a situation where this isn't enough I would recommend you to use Google Colab or Kaggle Kernels. Both are free and give you access to a powerful GPU.

Kind regards,
Gilbert Tanner

**Comment by AGenchev** [comment]
OK, thanks ! Then I close this. I didn't know that there were free online GPUs - thans I'll try them.
I have something new with more ram, it just is not a notebook - a jetson tx2.
